### PR TITLE
Merge current NeuronRobotics master

### PR DESCRIPTION
**Pull request by msteigenberger**
Merged current state of NeuronRobotics master branch from https://github.com/NeuronRobotics/nrjavaserial

### CODE REVIEW

**Comment by kaikreuzer** [comment]
We imho should not merge the remote master on our modified master - this will result in a messy history and state.

As can be seen on https://github.com/openhab/nrjavaserial/commits/master, our current master is the "official" master plus 3 commits from @cvanorman on top, one of which you are reverting with https://github.com/openhab/nrjavaserial/pull/7.

What isn't clear to me is whether commits https://github.com/openhab/nrjavaserial/commit/be9568134653a81dc8f1b673c4c6a6a120219c09 and https://github.com/openhab/nrjavaserial/commit/8750b9593a141cb7c8ef36ffaf03ba1a4ba66be6 are still required by us? If not, all that we would need is the latest official master with https://github.com/openhab/nrjavaserial/pull/4 being merged on it, right?
If this is the case, did anyone try out version 3.13.0 and can confirm that it works with openHAB?
@msteigenberger If we update our fork, are you able to build a binary from it? (or @cvanorman, are you still around and could help here?)

**Comment by msteigenberger** [comment]
8750b9593a141cb7c8ef36ffaf03ba1a4ba66be6 is not required anymore.
But if be9568134653a81dc8f1b673c4c6a6a120219c09 is required I don't know. @cvanorman, can you comment on this?

Then I would also go for a clean 'official' master.

@kaikreuzer: Don't we have a CI build for the fork? Where to upload the binary if build? The native binaries I think are already pre-build and commited, so no need to build them. The jar is build with gradle -> should be no problem.

**Comment by kaikreuzer** [comment]
> Don't we have a CI build for the fork? 

No, we don't.

> Where to upload the binary if build?

I did that by manually deploying it to https://bintray.com/openhab/p2/nrjavaserial/3.12.0#files/nrjavaserial%2F3.12.0 from where the build picks it up.

> so no need to build them

That's good.

**Comment by kaikreuzer** [comment]
> Then I would also go for a clean 'official' master.

I have just switched our fork to the latest official master.

**Pull request closed without merging**
