### PR TITLE
Include rfc2217 classes without fat jar

### PR DESCRIPTION
**Pull request by msteigenberger**
RFC2217 classes are included again (as I'd need it in openhab).
The dependencies to apache.commons.lang and apache.commons.net are not included in the jar anymore (which was the initial cause of that change).

Dependency to apache.commons.net is done by Import-Package OSGI instruction.

This reverts commit 9858f088d264a4743caa31b096edfe2b3aef719b.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Please note that this repo here has only been created for temporary use as long as the official repo was stale - luckily, it [seems to be back to life](https://github.com/NeuronRobotics/nrjavaserial/pull/98#issuecomment-302426092) again.
The 3.13.0 release seems to contain the RFC2217 classes (and it isn't a fat jar either). Could you test that version and file any potential issues with it directly at https://github.com/NeuronRobotics/nrjavaserial/issues? I'd hope that we can move back to an official release soon for openHAB and delete this fork here.

**Comment by martinvw** [comment]
@msteigenberger any progress on this?

**Comment by msteigenberger** [comment]
Hi, sorry for late response.
I've seen that nrjavaserial 3.13.0 introduced a new dependency to _JNA_ with a package import _"com.sun.jna.platform.win32"_. As long as I've seen we don't have that dependency already in any other bundle.
It was introduced in following commit: https://github.com/NeuronRobotics/nrjavaserial/commit/332983b75fcff146f1bcd7226f4edb3f5eec9340

Is it feasible to get JNA included in openhab?

**Comment by martinvw** [comment]
@msteigenberger I do not really understand what you mean, do you mean it does not work because of that *JNA* dependency and that we need both the nrjavaserial and jna for it to work? Will it fail otherwise?

Could you report it there? Or is the only possibility for us to include JNA?

**Comment by msteigenberger** [comment]
I've not tried it, but as there is an import package to the package com.sun.jna.platform.win32 and no bundle exporting this -> nrjavaserial bundle will not be resolved.

I don't think that nrjavaserial project will resolve it, as they would then need to either revert the mentioned commit, extract it to some optional thing, or resolve it by other means.
They need Registry access, which could basically be done like mentioned here: https://stackoverflow.com/questions/62289/read-write-to-windows-registry-using-java. But honestly I would also use a library for that...

They introduced it because of a performance increase on windows platform.

I saw that openhab uses JNA in the "org.openhab.binding.systeminfo" bundle. But only as "Bundle-Classphath" library.
Is there any possibility to use JNA as OSGI Bundle? It already has an OSGI Manifest.

**Comment by martinvw** [comment]
@kaikreuzer wdyt?

**Comment by msteigenberger** [comment]
I saw that it was already covered in https://github.com/NeuronRobotics/nrjavaserial/pull/100.
But solution was to make it optional, which would cause the bundle to resolve. But it will fail at runtime, as this package is NOT optional.

**Comment by kaikreuzer** [comment]
I have answered on https://github.com/NeuronRobotics/nrjavaserial/pull/100#issuecomment-323544370.
@msteigenberger For rfc2217 support, we should rather look at getting back on an official version of nrjavaserial again instead of doing changes on this fork here, so I'll close this PR.

**Comment by msteigenberger** [comment]
@kaikreuzer Sure, fully agree.
Should I open an Issue in openhab repo regarding JNA?

**Comment by kaikreuzer** [comment]
@msteigenberger I assume that you do not have any compile time dependency against JNA, so the easiest option would be to add the JNA bundle to your binding's Karaf feature definition in feature.xml.

**Comment by msteigenberger** [comment]
@kaikreuzer: Yes, you're right that would be probably the easiest option until the https://github.com/NeuronRobotics/nrjavaserial/pull/109 is resolved.
Thanks for pointing this out.

But it will not work from marketplace as the dependencies are not getting resolved, right?

**Pull request closed without merging**
